import{S as q,i as n}from"./assets/vendor-Dg3uDB0e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="56116338-e065c09dde8a76b57de900d0e";async function f(o,t){const a=`https://pixabay.com/api/?key=${S}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`,s=await fetch(a);if(!s.ok)throw new Error("Failed to fetch images");return await s.json()}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:c,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${c}</span></p>
        <p class="info-item"><b>Comments</b><span>${w}</span></p>
        <p class="info-item"><b>Downloads</b><span>${v}</span></p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){m.innerHTML=""}function g(){h.classList.remove("is-hidden")}function u(){h.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const P=document.querySelector("#search-form"),B=document.querySelector(".load-more");let l="",i=1;const L=15;P.addEventListener("submit",O);B.addEventListener("click",E);async function O(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){n.warning({message:"Please enter a search query!"});return}i=1,M(),d(),g();try{const t=await f(l,i);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}p(t.hits);const a=Math.ceil(t.totalHits/L);i>=a?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{n.error({message:"An error occurred while fetching images."})}finally{u()}}async function E(){i+=1,d(),g();try{const o=await f(l,i);p(o.hits),setTimeout(()=>{const a=document.querySelector(".gallery-item");if(a){const{height:s}=a.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}},100);const t=Math.ceil(o.totalHits/L);i>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{n.error({message:"Failed to load more images."})}finally{u()}}
//# sourceMappingURL=index.js.map
