import{a as q,S,i as n}from"./assets/vendor-CgWX3-ZD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="56116338-e065c09dde8a76b57de900d0e";async function m(o,t){const s=`https://pixabay.com/api/?key=${$}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=15`;return(await q.get(s)).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:c,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${c}</span></p>
        <p class="info-item"><b>Comments</b><span>${w}</span></p>
        <p class="info-item"><b>Downloads</b><span>${v}</span></p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){f.innerHTML=""}function g(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const B=document.querySelector("#search-form"),O=document.querySelector(".load-more");let l="",i=1;const L=15;B.addEventListener("submit",H);O.addEventListener("click",I);async function H(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){n.warning({message:"Please enter a search query!"});return}i=1,P(),d(),g();try{const t=await m(l,i);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}h(t.hits);const s=Math.ceil(t.totalHits/L);i>=s?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{n.error({message:"An error occurred while fetching images."})}finally{u()}}async function I(){i+=1,d(),g();try{const o=await m(l,i);h(o.hits),setTimeout(()=>{const s=document.querySelector(".gallery-item");if(s){const{height:a}=s.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}},100);const t=Math.ceil(o.totalHits/L);i>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{n.error({message:"Failed to load more images."})}finally{u()}}
//# sourceMappingURL=index.js.map
