import{S as q,i as n,a as S}from"./assets/vendor-CgWX3-ZD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:c,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${r}</span></p>
        <p class="info-item"><b>Views</b><span>${c}</span></p>
        <p class="info-item"><b>Comments</b><span>${w}</span></p>
        <p class="info-item"><b>Downloads</b><span>${v}</span></p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){f.innerHTML=""}function g(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}function b(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const $=document.querySelector("#search-form"),B=document.querySelector(".load-more"),O="56116338-e065c09dde8a76b57de900d0e";let l="",i=1;const m=15;$.addEventListener("submit",H);B.addEventListener("click",T);async function L(o,t){const s={params:{key:O,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:m}};return(await S.get("https://pixabay.com/api/",s)).data}async function H(o){if(o.preventDefault(),l=o.currentTarget.elements.searchQuery.value.trim(),!l){n.warning({message:"Please enter a search query!"});return}i=1,P(),d(),g();try{const t=await L(l,i);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}h(t.hits);const s=Math.ceil(t.totalHits/m);i>=s?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{n.error({message:"An error occurred while fetching images."})}finally{u()}}async function T(){i+=1,d(),g();try{const o=await L(l,i);h(o.hits),setTimeout(()=>{const s=document.querySelector(".gallery-item");if(s){const{height:a}=s.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}},100);const t=Math.ceil(o.totalHits/m);i>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b()}catch{n.error({message:"Failed to load more images."})}finally{u()}}
//# sourceMappingURL=index.js.map
